apiVersion: v1
kind: ConfigMap
metadata:
  labels:
  {{- include "pythondatabricksta.labels" . | nindent 4 }}
  name: {{ template "pythondatabricksta.fullname" . }}-config
data:
  application.yaml: |
  {{- if .Values.configOverride -}}
  {{- .Values.configOverride | nindent 4 }}
  {{- else -}}
  {{- .Files.Get "files/application.yml" | nindent 4 }}
  {{- end }}
