# Default values for python-databricks-tech-adapter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Docker Registry Secret name used to access a private repo
dockerRegistrySecretName: regcred

image:
  # -- Image repository
  registry: registry.gitlab.com/agilefactory/witboost.mesh/provisioning/witboost.mesh.provisioning.databricks.python
  # -- Image tag
  tag: latest
  # -- The imagePullPolicy for a container and the tag of the image affect when the kubelet attempts to pull (download) the specified image.
  pullPolicy: Always

# -- define extra variables to add to the container(s), like the Azure permissions configurations if necessary
# e.g:
# extraEnvVars:
#   - name: FOO
#     value: "10"
extraEnvVars:
  - name: GIT__USERNAME
    valueFrom:
      secretKeyRef:
        name: databricks-addons-secrets
        key: GIT_USERNAME
  - name: GIT__TOKEN
    valueFrom:
      secretKeyRef:
        name: databricks-addons-secrets
        key: GIT_TOKEN
  - name: AZURE_TENANT_ID
    valueFrom:
      secretKeyRef:
        name: databricks-addons-secrets
        key: AZURE_TENANT_ID
  - name: AZURE_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: databricks-addons-secrets
        key: AZURE_CLIENT_SECRET
  - name: AZURE_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: databricks-addons-secrets
        key: AZURE_CLIENT_ID
  - name: DATABRICKS__AUTH__ACCOUNT_ID
    valueFrom:
      secretKeyRef:
        name: databricks-addons-secrets
        key: DATABRICKS_ACCOUNT_ID

# -- readiness probe spec
readinessProbe: {}

# -- liveness probe spec
livenessProbe: {}

# -- security context spec
securityContext:
  runAsUser: 1001
  allowPrivilegeEscalation: false
  runAsNonRoot: true

# -- resources spec
resources: {}

# -- Allows you to specify common labels
labels: {}


